export const productos = [
    {
        id: 1,
        nombre: "Amazfit GTS 2 Mini",
        precio: 12000,
        categoria: "smartwatch",
        stock: 17,
        color: "negro",
        img: "",
    },
    {
        id: 2,
        nombre: "DT PRO 88",
        precio: 15000,
        categoria: "smartwatch",
        stock: 15,
        color: "negro",
        img: "",
    },
    {
        id: 3,
        nombre: "DT100 PRO MAX",
        precio: 19999,
        categoria: "smartwatch",
        stock: 20,
        color: "plateado",
        img: "",
    },
    {
        id: 4,
        nombre: "W26",
        precio: 13000,
        categoria: "smartwatch",
        stock: 12,
        color: "blanco",
        img: "",
    },
    {
        id: 5,
        nombre: "REDMI AirDots Xiaomi",
        precio: 11000,
        categoria: "auriculares",
        stock: 15,
        color: "negro",
        img: "",
    },
    {
        id: 6,
        nombre: "InPods I12",
        precio: 9999,
        categoria: "auriculares",
        stock: 15,
        color: "celeste",
        img: "",
    }
]